### ISSUE TITLE
[support request]

### ISSUE THREAD

**Issue by ThanasisBarekas** [fonimus/ssh-shell-spring-boot#252]
Hello, 

I hope i am finding you happy and well :) I have a problem that you might be able to help me. After I upgraded spring boot parent to 2.7.5 and ssh-shell-spring-boot-starter to 2.0.2 and made some code changes that were needed my app works fine but i get this strange error in my logs : 

No command found for '--spring.config.location=C:/Users/barekas/Documents/Repos/ztc_cli_connector/src/cli/target/cliServer-bin/cliServer/config/application-dev.yml'
org.springframework.shell.CommandNotFound: No command found for '--spring.config.location=C:/Users/barekas/Documents/Repos/ztc_cli_connector/src/cli/target/cliServer-bin/cliServer/config/application-dev.yml'
        at org.springframework.shell.Shell.evaluate(Shell.java:231)
        at com.github.fonimus.ssh.shell.ExtendedShell.evaluate(ExtendedShell.java:112)
        at com.github.fonimus.ssh.shell.ExtendedShell.run(ExtendedShell.java:102)
        at com.github.fonimus.ssh.shell.ExtendedShell.run(ExtendedShell.java:75)
        at org.springframework.shell.jline.NonInteractiveShellRunner.run(NonInteractiveShellRunner.java:104)
        at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:65)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at com.cli.CliStarter.main(CliStarter.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

Also i get some nullpointer exception in my integration tests ...

It seems that it has some problem with my application properties file. Any clue ?
Do you need some info from my application.yml file ?

Thank you,
Thanasis

**Comment by ThanasisBarekas** [comment]
In Debug mode it seems that this is the root cause 
2022-10-22 23:16:28.336 [main] DEBUG org.springframework.shell.Shell - Evaluate input with line=[--spring.config.location=C:/Users/barekas/Documents/Repos/ztc_cli_connector/src/cli/target/cliServer-bin/cliServer/config/application-dev.yml], command=[null]

But I dont get which command is null. 

Here is my related ssh application yml config :  

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart.max-file-size: -1
    multipart.max-request-size: -1

ssh:
  shell:
    authentication: security
    auth-provider-bean-name: customAuthManager
    port: 2223
    host: 0.0.0.0
    commands:
      actuator:
        create: false
        enable: false
        restricted: true
        # empty by default
        excludes:
          - ...
        authorized-roles:
          - ACTUATOR
      # since 1.4.0
      jmx:
        create: false
        enable: false
        restricted: true
        authorized-roles:
          - ADMIN
      system:
        create: false
        enable: false
        restricted: true
        authorized-roles:
          - ADMIN
      # since 1.4.0
      datasource:
        create: false
        enable: false
        restricted: true
        authorized-roles:
          - ADMIN
        excludes:
          - datasource-update
      postprocessors:
        create: false
        enable: false
        restricted: false
      # history and script added in 1.8.0
      history:
        create: true
        enable: true
        restricted: false
      script:
        create: true
        enable: false
        restricted: false
      # since 1.3.0, command which allows you to list ssh sessions, and stop them
      manage-sessions:
        create: false
        enable: false
        restricted: true
        authorized-roles:
          - ADMIN
      # since 1.5.0
      tasks:
        create: false
        enable: false
        restricted: true
        authorized-roles:
          - ADMIN

**Comment by ThanasisBarekas** [comment]
I found the problem in my tests, this config was missing "spring.shell.interactive.enabled=false" but the exception in my logs I cant find :) 

Thank you,
Thanasis

**Comment by fonimus** [comment]
I am glad you figured out so quickly ;)
Closing this issue
